# Dockerfile for python 
# Version 1.0
FROM prom/prometheus

MAINTAINER Christian Zunker <christian.zunker@codecentric.de>

ADD prometheus.conf /prometheus.conf

#RUN /go/src/github.com/prometheus/prometheus/prometheus -logtostderr -config.file=/prometheus.conf -web.console.libraries=/go/src/github.com/prometheus/prometheus/console_libraries -web.console.templates=/go/src/github.com/prometheus/prometheus/consoles
